# Generated by Django 5.1.1 on 2024-10-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante_curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estudiantecurso',
            table='Estudiantes_Cursos',
        ),
    ]
