# Generated by Django 5.1.1 on 2024-10-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_persona_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
