# Generated by Django 5.1.1 on 2024-10-13 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('persona', '0002_alter_persona_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='capacidad_max',
            field=models.CharField(default=30, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, related_name='cursos_estudiante', to='persona.persona'),
        ),
    ]
