# Generated by Django 5.1.1 on 2024-10-13 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_capacidad_max_curso_estudiantes'),
        ('persona', '0003_rename_create_at_persona_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='create_at',
        ),
        migrations.AlterField(
            model_name='curso',
            name='capacidad_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='persona.persona'),
        ),
    ]
